Module Module1

    Sub Main()
        Dim myQueue As New CircularQueue(Of String)(10)
        myQueue.Enqueue("test1")
        myQueue.Enqueue("test2")
        myQueue.Enqueue("test3")
        myQueue.Enqueue("test4")
        myQueue.Enqueue("test5")
        myQueue.Enqueue("test6")
        myQueue.Enqueue("test1")
        myQueue.Enqueue("test2")
        myQueue.Enqueue("test3")
        myQueue.Enqueue("test6")
        myQueue.Enqueue("test1")
        myQueue.Enqueue("test2")
        myQueue.Enqueue("test3")
        myQueue.Enqueue("test6")
        myQueue.Enqueue("test1")
        myQueue.Enqueue("test2")
        myQueue.Enqueue("test3")
        Console.WriteLine(myQueue.DeQueue)
        Console.WriteLine(myQueue.DeQueue)
        Console.WriteLine(myQueue.DeQueue)
        Console.WriteLine(myQueue.Peek)
        Console.WriteLine(myQueue.DeQueue)
        myQueue.Enqueue("test6")
        myQueue.Enqueue("test1")
        myQueue.Enqueue("test2")
        myQueue.Enqueue("test6")
        myQueue.Enqueue("test1")
        myQueue.Enqueue("test2")
        myQueue.Enqueue("test3")
        myQueue.Enqueue("test3")
        Console.WriteLine(myQueue.DeQueue)
        Console.WriteLine(myQueue.Peek)
        Console.WriteLine(myQueue.DeQueue)
        Console.ReadKey()
    End Sub

End Module
